[package]
name = "async-io"
version = "0.1.6"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "Async I/O and timers"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/stjepang/async-io"
homepage = "https://github.com/stjepang/async-io"
documentation = "https://docs.rs/async-io"
keywords = ["mio", "epoll", "kqueue", "iocp", "wepoll"]
categories = ["asynchronous", "network-programming", "os"]
readme = "README.md"

[dependencies]
cfg-if = "0.1.10"
concurrent-queue = "1.1.2"
futures-lite = "0.1.9"
libc = "0.2.73"
once_cell = "1.4.0"
parking = "1.0.6"
socket2 = { version = "0.3.12", features = ["pair", "unix"] }
vec-arena = "0.5.0"

[target.'cfg(windows)'.dependencies]
wepoll-sys-stjepang = "1.0.6"
winapi = { version = "0.3.9", features = ["ioapiset"] }

[dev-dependencies]
async-channel = "1.1.1"
async-dup = "1.2.1"
blocking = "0.5.0"
signal-hook = "0.1.16"
tempfile = "3.1.0"
waker-fn = "1.0.0"

[target.'cfg(target_os = "linux")'.dev-dependencies]
inotify = { version = "0.8.3", default-features = false }
nix = "0.17.0"
timerfd = "1.1.1"

[target.'cfg(windows)'.dev-dependencies]
uds_windows = "0.1.5"
